name: cs4nlp
channels:
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.2
  - cloudpickle=2.1.0
  - colorama=0.4.4
  - cryptography=36.0.2
  - cycler=0.11.0
  - dash=2.4.1
  - dash_cytoscape=0.2.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - dill=0.3.5.1
  - entrypoints=0.4
  - executing=0.8.3
  - flask=2.1.2
  - flask-compress=1.12
  - fonttools=4.32.0
  - freetype=2.10.4
  - gevent=21.12.0
  - giflib=5.2.1
  - greenlet=1.1.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - ipykernel=6.12.1
  - ipython=8.2.0
  - itsdangerous=2.1.2
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - keras=2.8.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=13.0.1
  - libdeflate=1.10
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - lime=0.2.0.1
  - llvm-openmp=13.0.1
  - llvmlite=0.38.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - multiprocess=0.70.13
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nltk=3.6.7
  - numba=0.55.1
  - numpy=1.21.6
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - parso=0.8.3
  - pathos=0.2.9
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - plotly=5.8.0
  - pox=0.3.1
  - ppft=1.7.6.5
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - pyzmq=22.3.0
  - readline=8.1
  - regex=2022.3.15
  - request=2.83.1
  - requests=2.27.1
  - salib=1.4.5
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=62.0.0
  - shap=0.40.0
  - six=1.16.0
  - slicer=0.0.7
  - sqlite=3.37.1
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tenacity=8.0.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - werkzeug=2.1.2
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.5.2
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==21.4.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - blis==0.7.7
    - catalogue==2.0.7
    - cymem==2.0.6
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - defusedxml==0.7.1
    - fastjsonschema==2.15.3
    - imageio==2.19.3
    - importlib-resources==5.7.1
    - interpret==0.2.7
    - interpret-core==0.2.7
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - it-core-news-sm==3.3.0
    - jsonschema==4.5.1
    - jupyter==1.0.0
    - jupyter-console==6.4.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - langcodes==3.3.0
    - mistune==0.8.4
    - murmurhash==1.0.7
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - networkx==2.8.3
    - notebook==6.4.11
    - pandarallel==1.6.1
    - pandocfilters==1.5.0
    - pathy==0.6.1
    - preshed==3.0.6
    - prometheus-client==0.14.1
    - pydantic==1.8.2
    - pyrsistent==0.18.1
    - pywavelets==1.3.0
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - scikit-image==0.19.2
    - send2trash==1.8.0
    - skope-rules==1.0.1
    - smart-open==5.2.1
    - soupsieve==2.3.2.post1
    - spacy==3.3.0
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - srsly==2.4.3
    - tdqm==0.0.1
    - terminado==0.15.0
    - thinc==8.0.16
    - tifffile==2022.5.4
    - tinycss2==1.1.1
    - treeinterpreter==0.2.3
    - typer==0.4.1
    - typing-extensions==4.2.0
    - wasabi==0.9.1
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - wikiextractor==3.0.6
    - wordcloud==1.8.1
